# Server configuration
server:
  port: 8080

# Spring Boot configuration
spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quadrant_equation
    username: postgres
    password: 137qwerty