CREATE TABLE IF NOT EXISTS quadratic_equation (
    id    INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    a     double precision,
    b     double precision,
    c     double precision,
    x1    double precision,
    x2    double precision
);